name: Streak Protector Auto Commit

permissions:
  contents: write

on:
  schedule:
    # Runs at 06:00 AM IST every day (00:30 UTC)
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up commit identity
        run: |
          git config --local user.email "jayanthdonavalli0124@gmail.com"
          git config --local user.name "Jayanth0124"

      - name: Ensure counter file exists
        run: |
          if [ ! -f counter.txt ]; then
            echo "Commit No: 0" > counter.txt
          fi

      - name: Increment commit counter
        run: |
          COUNT=$(grep -o '[0-9]*' counter.txt)
          COUNT=$((COUNT + 1))
          echo "Commit No: $COUNT" > counter.txt
          git add counter.txt
          git commit -m "New Update: $COUNT"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
